#!/usr/bin/env python3
"""Regenerate the thin image inputs from an official Omnigent release."""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path


NAME_RE = re.compile(r"[-_.]+")
RELEASE_RE = re.compile(r"^v[0-9]+\.[0-9]+\.[0-9]+$")
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
REQUIREMENT_NAME_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)")


def normalize_name(name: str) -> str:
    return NAME_RE.sub("-", name).lower()


def dependency_closure(lock: dict, roots: set[str]) -> list[dict]:
    by_name: dict[str, list[dict]] = {}
    for package in lock.get("package", []):
        by_name.setdefault(normalize_name(package["name"]), []).append(package)

    selected: dict[str, dict] = {}
    pending = sorted(roots)
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        candidates = by_name.get(name, [])
        if len(candidates) != 1:
            raise ValueError(
                f"expected exactly one locked package for {name!r}, found {len(candidates)}"
            )
        package = candidates[0]
        if package.get("source", {}).get("registry") != "https://pypi.org/simple":
            raise ValueError(f"S3 dependency {name!r} is not locked from PyPI")
        selected[name] = package
        pending.extend(
            normalize_name(dependency["name"])
            for dependency in package.get("dependencies", [])
            if normalize_name(dependency["name"]) not in selected
        )
    return [selected[name] for name in sorted(selected)]


def render_requirements(packages: list[dict], release: str) -> str:
    lines = [
        f"# Generated from Omnigent {release}'s uv.lock by scripts/update_upstream.py.",
        "# Do not edit manually.",
    ]
    for package in packages:
        hashes = sorted(
            {
                wheel["hash"]
                for wheel in package.get("wheels", [])
                if wheel.get("hash", "").startswith("sha256:")
            }
        )
        if not hashes:
            raise ValueError(f"locked package {package['name']!r} has no SHA-256 wheel")
        lines.append(f"{package['name']}=={package['version']} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash={digest}{suffix}")
    return "\n".join(lines) + "\n"


def render_dockerfile(release: str, digest: str, packages: list[dict]) -> str:
    derived_version = f"{release}-s3.1"
    versions = {normalize_name(p["name"]): p["version"] for p in packages}
    checks = "; ".join(
        [
            "import importlib.metadata as m",
            *(f'assert m.version("{name}") == "{versions[name]}"' for name in sorted(versions)),
        ]
    )
    return f"""# syntax=docker/dockerfile:1.7
# Generated by scripts/update_upstream.py. Do not edit manually.
ARG BASE_IMAGE=ghcr.io/omnigent-ai/omnigent-server:{release}@{digest}
FROM ${{BASE_IMAGE}}

USER root
COPY requirements-s3.txt /tmp/requirements-s3.txt
RUN /opt/venv/bin/pip install \\
      --disable-pip-version-check \\
      --no-cache-dir \\
      --only-binary=:all: \\
      --require-hashes \\
      --requirement /tmp/requirements-s3.txt \\
    && /opt/venv/bin/python -c '{checks}' \\
    && rm -f /tmp/requirements-s3.txt

LABEL org.opencontainers.image.title="Omnigent server with S3 support" \\
      org.opencontainers.image.description="Thin derivative of Omnigent {release} with its locked S3 dependencies" \\
      org.opencontainers.image.source="https://github.com/reonokiy/omnigent-s3" \\
      org.opencontainers.image.licenses="Apache-2.0" \\
      org.opencontainers.image.version="{derived_version}" \\
      org.opencontainers.image.base.name="ghcr.io/omnigent-ai/omnigent-server:{release}"
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--release", required=True)
    parser.add_argument("--digest", required=True)
    parser.add_argument("--pyproject", required=True, type=Path)
    parser.add_argument("--lock", required=True, type=Path)
    parser.add_argument("--root", default=Path.cwd(), type=Path)
    args = parser.parse_args()

    if not RELEASE_RE.fullmatch(args.release):
        raise ValueError(f"not a stable release tag: {args.release!r}")
    if not DIGEST_RE.fullmatch(args.digest):
        raise ValueError(f"not an OCI SHA-256 digest: {args.digest!r}")

    pyproject = tomllib.loads(args.pyproject.read_text())
    extra = pyproject["project"]["optional-dependencies"]["s3"]
    roots: set[str] = set()
    for requirement in extra:
        match = REQUIREMENT_NAME_RE.match(requirement)
        if not match:
            raise ValueError(f"cannot parse S3 requirement: {requirement!r}")
        roots.add(normalize_name(match.group(1)))
    if not {"boto3", "botocore"}.issubset(roots):
        raise ValueError("upstream s3 extra no longer contains boto3 and botocore")

    lock = tomllib.loads(args.lock.read_text())
    packages = dependency_closure(lock, roots)
    derived_version = f"{args.release}-s3.1"
    args.root.joinpath("requirements-s3.txt").write_text(
        render_requirements(packages, args.release)
    )
    args.root.joinpath("Dockerfile").write_text(
        render_dockerfile(args.release, args.digest, packages)
    )
    args.root.joinpath(".upstream-version").write_text(f"{args.release}\n")
    args.root.joinpath(".image-version").write_text(f"{derived_version}\n")
    print(f"generated {derived_version} with {len(packages)} locked S3 packages")


if __name__ == "__main__":
    main()
